puavo-post-ltsp-server-load: Remove tabs

diff --git a/bin/puavo-post-ltsp-server-load b/bin/puavo-post-ltsp-server-load
--- a/bin/puavo-post-ltsp-server-load
+++ b/bin/puavo-post-ltsp-server-load
@@ -14,25 +14,25 @@ PUAVO_DOMAIN=$(cat /etc/puavo/domain)
 
 while true; do
     if [ "${URL}" = "" ]; then
-	API_SERVER=$(dig +time=2 +tries=1 SRV _puavo-api._tcp.${PUAVO_DOMAIN} +search +short | awk '{ sub(/\.$/, ""); printf "%s:%s", $4, $3 }')
+    API_SERVER=$(dig +time=2 +tries=1 SRV _puavo-api._tcp.${PUAVO_DOMAIN} +search +short | awk '{ sub(/\.$/, ""); printf "%s:%s", $4, $3 }')
 
-	if [ "${API_SERVER}" != "" ]; then
-	    HOSTNAME=$(hostname -f)
-	    URL="https://${API_SERVER}/v3/ltsp_servers/${HOSTNAME}"
-	else
-	    echo "Missing URL and _puavo-api._tcp.${PUAVO_DOMAIN} did not return anything!"
-	    exit 1
-	fi
+    if [ "${API_SERVER}" != "" ]; then
+        HOSTNAME=$(hostname -f)
+        URL="https://${API_SERVER}/v3/ltsp_servers/${HOSTNAME}"
+    else
+        echo "Missing URL and _puavo-api._tcp.${PUAVO_DOMAIN} did not return anything!"
+        exit 1
+    fi
     fi
 
     echo
     echo `date`
 
     curl --config - \
-	--request PUT \
-	--max-time 5 \
-	--cacert /etc/puavo/certs/rootca.pem \
-	$URL << EOF || true
+    --request PUT \
+    --max-time 5 \
+    --cacert /etc/puavo/certs/rootca.pem \
+    $URL << EOF || true
 data="cpu_count=$cpu_count"
 data="load_avg=$load_avg"
 data="ltps_image=$(cat /etc/ltsp/this_ltspimage_name || true)"
